version: "3"

services:
  amqporder:
    image: amqporder:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:~/amqporder;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=order;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  amqppayment:
    image: amqppayment:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:~/amqppayment;DB_CLOSE_ON_EXIT=FALSE;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  gateway:
    image: gateway:latest
    ports:
      - '9080:9080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  inventoryservice:
    image: inventoryservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:~/inventory;DB_CLOSE_ON_EXIT=FALSE;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  productservice:
    image: productservice:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:~/product;DB_CLOSE_ON_EXIT=FALSE;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  springtest:
    image: springtest:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=user;
    depends_on:
      - rabbitmq-dev
      - consul-importer
    networks:
      - microservices

  consul-importer:
    image: consul-importer:1.9
    depends_on:
      - consul-dev
    networks:
      - microservices

  consul-dev:
    image: consul:1.9
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
    networks:
      - microservices

  rabbitmq-dev:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices

  h2-server-dev:
    image: h2-server:2.1.214
    container_name: h2-server
    ports:
      - '81:81'
      - '1521:1521'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
